# SEO tag
title: Festiwal Wina Domowego
description: Festiwal wina domowego zrzeszający miłośników domowych trunków z Gilowic i okolic
url: "https://fewido.pl"
twitter:
  username: FeWiDo2021
  card: summary
social:
  name: FEWIDO
  links:
    - https://twitter.com/FeWiDo2021
    - https://www.instagram.com/fewido/

baseurl: "" # the subpath of your site, e.g. /blog
plugins:
  - jekyll-seo-tag
  - jekyll-feed
