# SEO tag
title: Festiwal Wina Domowego
url: "https://fewido.pl"
locale: "pl_PL"
twitter:
  username: FeWiDo2021
  card: summary
social:
  name: FEWIDO
  links:
    - https://twitter.com/FeWiDo2021
    - https://www.instagram.com/fewido/

baseurl: "" # the subpath of your site, e.g. /blog
plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/fewido.png"
